services:
  dev:
    build:
      context: ..
      dockerfile: docker/images/${ROSDISTRO:-jazzy}/Dockerfile
    image: ekumenlabs/beluga-${ROSDISTRO:-jazzy}-dev
    hostname: beluga-${ROSDISTRO:-jazzy}-dev
    container_name: beluga-${ROSDISTRO:-jazzy}-dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: true
    tty: true
    user: ${USERID:-1000}:${GROUPID:-1000}
    privileged: ${PRIVILEGED_CONTAINER:-false}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ..:/ws/src/beluga
      - beluga_ccache:/home/developer/.ccache
    devices:
      - /dev/dri:/dev/dri
volumes:
  beluga_ccache:
