/**:
  ros__parameters:
    # Basic setup
    map_frame: map
    robot_frame: base_link
    max_range: 100.0
    resolution: 0.07
    prob_hit: 0.8
    prob_miss: 0.1
    thres_min: 0.12
    thres_max: 0.51
    map_save_dir: "/ws/"

    # Visualizations
    publish_pointcloud: false
    publish_vis_marker: false
    visualization_rate: 2.0

    # Sensor input
    apply_raw_sensor_data: true
    sources: [velodyne]
    velodyne:
      topic: velodyne_points
      sensor_origin_frame: velodyne

    # Remote mapping
    publish_updates: true
    publish_overwrites: true
    publish_sections: true
    section_update:
      rate: 1.0
      min_coord:
        x: -10.0
        y: -10.0
        z: -10.0
      max_coord:
        x: 10.0
        y: 10.0
        z: 10.0


